"""add audio_features table

Revision ID: 3df1a1e4edd6
Revises: 830827b0eda7
Create Date: 2026-09-07 09:50:52.461371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3df1a1e4edd6'
down_revision: Union[str, None] = '830827b0eda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_features',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('audio_file_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=True),
    sa.Column('transcript_version', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('extractor', sa.String(length=100), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['consultation_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_features_audio_file_id'), 'audio_features', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_audio_features_session_id'), 'audio_features', ['session_id'], unique=False)
    op.create_index(op.f('ix_audio_features_transcript_id'), 'audio_features', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_features_transcript_id'), table_name='audio_features')
    op.drop_index(op.f('ix_audio_features_session_id'), table_name='audio_features')
    op.drop_index(op.f('ix_audio_features_audio_file_id'), table_name='audio_features')
    op.drop_table('audio_features')
    # ### end Alembic commands ###
