"""add guardian fields to cases

Revision ID: a4d05486e8c9
Revises: 3df1a1e4edd6
Create Date: 2026-09-08 10:12:45.366539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4d05486e8c9'
down_revision: Union[str, None] = '3df1a1e4edd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('guardian_type', sa.Enum('PARENTS', 'FATHER', 'MOTHER', 'GRANDPARENTS', 'RELATIVE', 'FOSTER', 'FACILITY', 'OTHER', name='guardian_type', native_enum=False, length=20), nullable=True))
    op.add_column('cases', sa.Column('guardian_note', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'guardian_note')
    op.drop_column('cases', 'guardian_type')
    # ### end Alembic commands ###
